# Generated by Django 3.1.1 on 2021-03-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210216_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
