# Generated by Django 3.0.7 on 2021-01-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210113_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
