# Generated by Django 3.0.7 on 2021-02-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210113_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='bid',
            new_name='current_bid',
        ),
    ]
