# Generated by Django 3.1.1 on 2020-12-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201231_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='user_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
