# Generated by Django 3.1.1 on 2021-01-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210103_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owners',
            new_name='UserListings',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
