# Generated by Django 3.0.7 on 2021-01-04 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210103_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistings',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='userlistings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userlistings',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings'),
        ),
        migrations.AddField(
            model_name='userlistings',
            name='listing_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
