# Generated by Django 3.0.7 on 2021-01-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210104_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='listing_id',
            field=models.CharField(default=None, max_length=99),
        ),
    ]
